language: node_js
node_js:
  - "lts/*"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sshpass
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn install
script:
  - yarn run build
cache:
  yarn: true
  directories:
    - "node_modules"
addons:
  ssh_known_hosts: biochem.sparker.xyz
deploy:
  provider: script
  skip_cleanup: true
  script:  sshpass -p "$SERVER_PWD" rsync -avz $TRAVIS_BUILD_DIR/dist/* root@biochem.sparker.xyz:/var/www/bioLab/backstage/
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
