language: node_js
node_js:
  - "node"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y sshpass yarn
install:
  - yarn install
script:
  - yarn run build
cache:
  directories:
  - "node_modules"
addons:
  ssh_known_hosts: 118.89.186.130
deploy:
  provider: script
  skip_cleanup: true
  script:  sshpass -p "$SERVER_PWD" rsync -avz $TRAVIS_BUILD_DIR/dist/* root@118.89.186.130:/var/www/bioLab/backstage/
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
