language: node_js
node_js:
    - "node"
install:
    - npm install
script:
    - npm run build
cache:
  directories:
    - "node_modules"
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -avz $TRAVIS_BUILD_DIR/dist root@118.89.186.130:/var/www/bioLab/backstage/
  on:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
